# Sensitive properties and secrets are hardcoded here strictly for local testing and educational purposes.
# In a production environment, these values are injected via environment variables (.env / OS ENV) following security best practices.

spring.datasource.url=jdbc:postgresql://localhost:5432/FactoryFlow
spring.datasource.username=postgres
spring.datasource.password=root
api.security.token.secret=8Aodh5kcg44m7h56v6j+9zCaWTLHcVa8ajrfV5vO/ls=
jwt.expiration=30